"""
Export trained student model to ONNX and TFLite formats.

Usage:
    python src/export_model.py --checkpoint trained_models/best_model.pt
    python src/export_model.py --checkpoint trained_models/best_model.pt --img-size 320
    python src/export_model.py --checkpoint trained_models/best_model.pt --quantize
"""
import argparse
import sys
from pathlib import Path

import torch
import torch.nn as nn
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))

from student.student_model import StudentSegmentation


class InferenceWrapper(nn.Module):
    """Wraps StudentSegmentation to return only the segmentation mask."""

    def __init__(self, model: StudentSegmentation):
        super().__init__()
        self.model = model

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        output, _ = self.model(x)
        return output


def export_onnx(model, dummy_input, output_path):
    """Export model to ONNX format."""
    print(f"Exporting ONNX to {output_path}...")
    torch.onnx.export(
        model,
        dummy_input,
        str(output_path),
        opset_version=18,
        input_names=["image"],
        output_names=["mask"],
        dynamic_axes={
            "image": {0: "batch"},
            "mask": {0: "batch"},
        },
    )
    size_mb = output_path.stat().st_size / (1024 * 1024)
    print(f"  ONNX saved: {size_mb:.2f} MB")


def export_tflite(onnx_path, output_path, quantize=False, calibration_data=None):
    """Convert ONNX model to TFLite."""
    try:
        import onnx2tf
    except ImportError:
        print("ERROR: onnx2tf not installed. Install with:")
        print("  pip install onnx2tf tensorflow onnx sng4onnx")
        return False

    print(f"Converting ONNX to TFLite...")

    # onnx2tf converts to SavedModel first, then to TFLite
    saved_model_dir = output_path.parent / "saved_model_tmp"

    onnx2tf.convert(
        input_onnx_file_path=str(onnx_path),
        output_folder_path=str(saved_model_dir),
        non_verbose=True,
    )

    # Find the generated .tflite file
    tflite_files = list(saved_model_dir.glob("*.tflite"))
    if not tflite_files:
        print("ERROR: No .tflite file generated by onnx2tf")
        return False

    # Use the float32 version as base
    src_tflite = tflite_files[0]

    if quantize and calibration_data is not None:
        print("Applying INT8 quantization...")
        success = _quantize_tflite(saved_model_dir, output_path, calibration_data)
        if not success:
            # Fall back to float model
            import shutil
            shutil.copy2(src_tflite, output_path)
    else:
        import shutil
        shutil.copy2(src_tflite, output_path)

    # Clean up temp dir
    import shutil
    shutil.rmtree(saved_model_dir, ignore_errors=True)

    if output_path.exists():
        size_mb = output_path.stat().st_size / (1024 * 1024)
        print(f"  TFLite saved: {size_mb:.2f} MB")
        return True
    return False


def _quantize_tflite(saved_model_dir, output_path, calibration_data):
    """Apply INT8 post-training quantization."""
    try:
        import tensorflow as tf
    except ImportError:
        print("WARNING: tensorflow not installed, skipping quantization")
        return False

    converter = tf.lite.TFLiteConverter.from_saved_model(str(saved_model_dir))
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    def representative_dataset():
        for sample in calibration_data:
            yield [sample.astype(np.float32)]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.uint8
    converter.inference_output_type = tf.uint8

    tflite_quant = converter.convert()
    with open(output_path, "wb") as f:
        f.write(tflite_quant)

    return True


def generate_calibration_data(img_size, num_samples=100):
    """Generate random calibration data for quantization."""
    print(f"Generating {num_samples} random calibration samples...")
    return [np.random.rand(1, 3, img_size, img_size) for _ in range(num_samples)]


def main():
    parser = argparse.ArgumentParser(description="Export student model to ONNX/TFLite")
    parser.add_argument("--checkpoint", type=str, required=True,
                        help="Path to trained checkpoint (best_model.pt)")
    parser.add_argument("--output-dir", type=str, default=None,
                        help="Output directory (default: same as checkpoint)")
    parser.add_argument("--img-size", type=int, default=640,
                        help="Input image size for export")
    parser.add_argument("--quantize", action="store_true",
                        help="Apply INT8 quantization to TFLite")
    parser.add_argument("--calibration-data", type=str, default=None,
                        help="Path to .npy calibration data for quantization")
    parser.add_argument("--onnx-only", action="store_true",
                        help="Only export ONNX, skip TFLite conversion")
    args = parser.parse_args()

    # Load checkpoint
    ckpt_path = Path(args.checkpoint)
    if not ckpt_path.exists():
        print(f"ERROR: Checkpoint not found: {ckpt_path}")
        sys.exit(1)

    print(f"Loading checkpoint: {ckpt_path}")
    checkpoint = torch.load(ckpt_path, map_location="cpu", weights_only=False)

    teacher_channels = checkpoint.get("teacher_channels", [256, 384, 256])
    ckpt_args = checkpoint.get("args", {})
    base_channels = ckpt_args.get("base_channels", 8)
    depth = ckpt_args.get("depth", 4)

    print(f"Model config: base_channels={base_channels}, depth={depth}")
    print(f"Teacher channels: {teacher_channels}")

    # Build model and load weights
    model = StudentSegmentation(
        in_channels=3,
        base_channels=base_channels,
        depth=depth,
        teacher_channels=teacher_channels,
    )
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {total_params:,}")

    # Wrap for inference (drops distill_info)
    wrapper = InferenceWrapper(model)
    wrapper.eval()

    # Output directory
    output_dir = Path(args.output_dir) if args.output_dir else ckpt_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # Dummy input for tracing
    dummy = torch.randn(1, 3, args.img_size, args.img_size)

    # Verify forward pass
    with torch.no_grad():
        out = wrapper(dummy)
    print(f"Output shape: {out.shape} (expected [1, 1, {args.img_size}, {args.img_size}])")

    # Export ONNX
    onnx_path = output_dir / f"student_seg_{args.img_size}.onnx"
    export_onnx(wrapper, dummy, onnx_path)

    if args.onnx_only:
        print("\nDone (ONNX only).")
        return

    # Export TFLite
    tflite_path = output_dir / f"student_seg_{args.img_size}.tflite"
    calibration_data = None
    if args.quantize:
        if args.calibration_data:
            calibration_data = np.load(args.calibration_data)
            calibration_data = [calibration_data[i:i+1] for i in range(len(calibration_data))]
        else:
            calibration_data = generate_calibration_data(args.img_size)

    success = export_tflite(onnx_path, tflite_path, args.quantize, calibration_data)

    if success:
        print(f"\nExport complete:")
        print(f"  ONNX:   {onnx_path}")
        print(f"  TFLite: {tflite_path}")
    else:
        print(f"\nONNX export complete: {onnx_path}")
        print("TFLite conversion failed — see errors above.")


if __name__ == "__main__":
    main()
